theme: minima
github: [metadata]
title: boris babenko, phd
encoding: UTF-8
permalink: /:title/
# kramdown:
#    input: GFM
#    hard_wrap: false
# gems:
#    - jekyll-coffeescript
#    - jekyll-paginate
exclude:
   - README.md
