theme: minima
github: [metadata]
title: boris babenko, phd
encoding: UTF-8
permalink: /:title/
include: ['_pages']
# gems:
#    - jekyll-coffeescript
#    - jekyll-paginate
exclude:
   - README.md
header_pages:
   - _pages/pubs.md
   - _pages/misc.md
disqus:
    shortname: website-11
